### ISSUE TITLE
company name

### ISSUE THREAD

**Issue by kaitlynharris** [Andrewearls/JobLeadGenerator#1]
Hey I remember that you were wanting this to be able to scrape for the company name.  From looking at a bunch of the ads, it seems like the most common place to find them is in the phrase "(company) is (verb)ing"  or "(company) is (verb)ed" so I bet you could use a regular expression to find matches for those phrases and generate a dropdown of possible names to insert. Something like /\b\w+?\b is \w+?(ing|ed)/ might work to pull them out.

**Comment by Andrewearls** [comment]
Hey Kaitlyn,
Thanks for the help the actual expression ended up being r"\b\w+?\b(?=( is a | is )\b\w+?(ed|ing)\b)" but I would have never gotten that far if not for your help. How's the job going for you?
-Andrew
